apiVersion: backstage.io/v1alpha1

app:
  title: The National Archives Backstage
  baseUrl: https://backstage.tna.dblclk.dev

organization:
  name: The National Archives

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

catalog:
  locations:
    - type: url
      target: https://github.com/nationalarchives/backstage-config/blob/main/catalog/nationalarchives.yaml
      rules:
        - allow: [Component, System, API, Resource, Location, Group, User]