apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: nationalarchives-website
  title: The National Archives website
  description: >
    The National Archives website, comprising a Wagtail CMS backend providing
    a content API and a Flask-based frontend application.
  tags:
    - website
    - cms
spec:
  owner: group:default/digital-services
